import Head from "next/head";
import Header from "./Header";
import style from "../styles/layout.module.css";
import Footer from "./Footer";

function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? `${title} | Amazon` : "Amazon"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/amz-logo.jpg" />
      </Head>

      <div className={style.layout}>
        <Header />

        <main className={style.layout__main}>{children}</main>

        <Footer />
      </div>
    </>
  );
}

export default Layout;
